-- MySQL Script generated by MySQL Workbench
-- Sat Jun 13 22:43:29 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema milk_factory
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `milk_factory` ;

-- -----------------------------------------------------
-- Schema milk_factory
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `milk_factory` DEFAULT CHARACTER SET utf8 ;
USE `milk_factory` ;

-- -----------------------------------------------------
-- Table `clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clients` ;

CREATE TABLE IF NOT EXISTS `clients` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `inn` VARCHAR(45) NULL,
  `addres` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `salesman` VARCHAR(45) NOT NULL,
  `buyer` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `materials`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `materials` ;

CREATE TABLE IF NOT EXISTS `materials` (
  `idmaterials` INT NOT NULL AUTO_INCREMENT,
  `materialsname` VARCHAR(255) NOT NULL,
  `price` DOUBLE NOT NULL,
  `materialscode` VARCHAR(255) NULL,
  `quantity` VARCHAR(10) NULL,
  PRIMARY KEY (`idmaterials`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `orders` ;

CREATE TABLE IF NOT EXISTS `orders` (
  `idorders` INT NOT NULL AUTO_INCREMENT,
  `clients_id` INT NOT NULL,
  `total` DOUBLE NULL,
  PRIMARY KEY (`idorders`),
  INDEX `fk_orders_clients1_idx` (`clients_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_clients1`
    FOREIGN KEY (`clients_id`)
    REFERENCES `clients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `orders_has_products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `orders_has_products` ;

CREATE TABLE IF NOT EXISTS `orders_has_products` (
  `orders_idorders` INT NOT NULL,
  `products_idproducts` INT NOT NULL,
  `count` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`orders_idorders`, `products_idproducts`),
  INDEX `fk_orders_has_products_products1_idx` (`products_idproducts` ASC) VISIBLE,
  INDEX `fk_orders_has_products_orders1_idx` (`orders_idorders` ASC) VISIBLE,
  CONSTRAINT `fk_orders_has_products_orders1`
    FOREIGN KEY (`orders_idorders`)
    REFERENCES `orders` (`idorders`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_has_products_products1`
    FOREIGN KEY (`products_idproducts`)
    REFERENCES `products` (`idproducts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `products` ;

CREATE TABLE IF NOT EXISTS `products` (
  `idproducts` INT NOT NULL AUTO_INCREMENT,
  `productsname` VARCHAR(255) NOT NULL,
  `price` DOUBLE NOT NULL,
  `productscode` VARCHAR(255) NULL,
  `quantity` VARCHAR(10) NULL,
  PRIMARY KEY (`idproducts`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `specifications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `specifications` ;

CREATE TABLE IF NOT EXISTS `specifications` (
  `products_idproducts` INT NOT NULL,
  `materials_idmaterials` INT NOT NULL,
  PRIMARY KEY (`products_idproducts`, `materials_idmaterials`),
  INDEX `fk_products_has_materials_materials1_idx` (`materials_idmaterials` ASC) VISIBLE,
  INDEX `fk_products_has_materials_products_idx` (`products_idproducts` ASC) VISIBLE,
  CONSTRAINT `fk_products_has_materials_products`
    FOREIGN KEY (`products_idproducts`)
    REFERENCES `products` (`idproducts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_has_materials_materials1`
    FOREIGN KEY (`materials_idmaterials`)
    REFERENCES `materials` (`idmaterials`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users` ;

CREATE TABLE IF NOT EXISTS `users` (
  `idusers` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `role` VARCHAR(45) NOT NULL DEFAULT 'user',
  `is_blocked` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idusers`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
